(defun gnuhealth-replace (a b &rest c)
  (goto-char (point-min))
  (when (and (re-search-forward (concat a "\"") nil t)
             (re-search-forward "msgstr \"" nil t))
    (delete-region (point) (line-end-position))
    (insert b)
    (insert "\""))
  (goto-char (point-min)))

(defun gnuhealth-generate-batch ()
  "Format a tab split file to a elisp function"
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward "\n+" nil t)
    (replace-match "\n" nil t))
  (goto-char (point-min))
  (while (re-search-forward "[[:space:]	\t]+" nil t)
    (replace-match "\" \"" nil t))
  (goto-char (point-min))
  (while (re-search-forward "^" nil t)
    (replace-match "(gnuhealth-replace \"" nil t))
  (while (re-search-forward "#N/A" nil t)
    (replace-match "" nil t))
  (goto-char (point-min))
  (while (re-search-forward "\n+" nil t)
    (replace-match "\")\n" nil t))
  (goto-char (point-min))
  (insert "
(defun gnuhealth_replace_all ()
  (interactive)
")
  (goto-char (point-max))
  (insert ")")
  )
